<?php

return [
    'top-nav' => [
        'order' => 1,
        'slug' => 'top-nav',
        'name' => 'الشريط العلوي',
        'description' => 'روابط وعناصر التنقل في أعلى الصفحة.',
        'icon' => 'assets/icons/tabler/layout-navbar.svg',
        'component' => 'tenant::components.top-nav',
        'editor' => 'admin::page.blocks.top-nav',
        'default' => true,
    ],
    'header' => [
        'order' => 2,
        'slug' => 'header',
        'name' => 'معلومات النشاط',
        'description' => 'العنوان الرئيسي والمقدمة في أعلى المحتوى.',
        'icon' => 'assets/icons/tabler/Heading.svg',
        'component' => 'tenant::components.header',
        'editor' => 'admin::page.blocks.header',
        'default' => true,
    ],
    'cta' => [
        'order' => 3,
        'slug' => 'cta',
        'name' => 'الأزرار السريعة (هدف الصفحة)',
        'description' => 'أضف زر رئيسي وأزرار ثانوية لدفع العميل لإتخاذ الإجراء المطلوب.',
        'icon' => 'assets/icons/tabler/Click.svg',
        'component' => 'tenant::components.cta',
        'editor' => 'admin::page.blocks.cta',
        'default' => true,
    ],
    'footer' => [
        'order' => 4,
        'slug' => 'footer',
        'name' => 'تذييل الصفحة',
        'description' => 'معلومات وروابط أسفل الصفحة.',
        'icon' => 'assets/icons/tabler/layout-bottombar.svg',
        'component' => 'tenant::components.footer',
        'editor' => 'admin::page.blocks.footer',
        'default' => true,
    ],
    'float-links' => [
        'order' => 5,
        'slug' => 'float-links',
        'name' => 'الأزرار الطافية',
        'description' => 'أزرار سريعة ثابتة للتواصل تظهر فوق الصفحة',
        'icon' => 'assets/icons/tabler/Link.svg',
        'component' => 'tenant::components.float-links',
        'editor' => 'admin::page.blocks.float-links',
        'default' => true,
    ],
    // 'link' => [
    //     'order' => 10,
    //     'slug' => 'link',
    //     'name' => 'رابط',
    //     'description' => 'رابط بسيط مع عنوان ووجهة.',
    //     'icon' => 'assets/icons/tabler/Link.svg',
    //     'component' => 'tenant::components.link',
    //     'editor' => 'admin::page.blocks.link',
    //     'default' => false,
    // ],
    'block-link' => [
        'order' => 11,
        'slug' => 'block-link',
        'name' => 'بطاقة الرابط',
        'description' => 'بطاقة رابط مع أيقونة وعنوان ووصف.',
        'icon' => 'assets/icons/tabler/ExternalLink.svg',
        'component' => 'tenant::components.block-link',
        'editor' => 'admin::page.blocks.block-link',
        'default' => false,
    ],
];
