<?php

return [
    'pages' => [
        'order' => 1,
        'active' => true,
        'default' => true,
        'sellable' => false,
        'slug' => 'pages',
        'model_type' => 'page',
        'name' => 'الصفحات',
        'description' => 'إنشاء وإدارة صفحات الموقع الثابتة والمخصصة.',
        'icon' => 'assets/icons/ecommerce/031-content.svg',
        'color' => 'blue',
        'components' => [
            'index' => 'admin::page.content.pages.index',
            'detail' => 'admin::page.content.pages.detail',
        ],
    ],
    'blog' => [
        'order' => 2,
        'active' => true,
        'default' => false,
        'sellable' => false,
        'slug' => 'blog',
        'model_type' => 'blog',
        'name' => 'المدونة',
        'description' => 'كتابة ونشر المقالات وتنظيم التصنيفات.',
        'icon' => 'assets/icons/stationery/002-book.svg',
        'color' => 'orange',
        'components' => [
            'index' => 'admin::page.content.blog.index',
            'detail' => 'admin::page.content.blog.detail',
        ],
    ],
    'portfolio' => [
        'order' => 3,
        'active' => true,
        'default' => false,
        'sellable' => false,
        'slug' => 'portfolio',
        'model_type' => 'portfolio',
        'name' => 'معرض الأعمال',
        'description' => 'عرض وإدارة مشاريعك وأعمالك السابقة.',
        'icon' => 'assets/icons/business/047-portfolio.svg',
        'color' => 'violet',
        'components' => [
            'index' => 'admin::page.content.portfolio.index',
            'detail' => 'admin::page.content.portfolio.detail',
        ],
    ],
    'forms' => [
        'order' => 4,
        'active' => true,
        'default' => false,
        'sellable' => false,
        'slug' => 'forms',
        'model_type' => 'form',
        'name' => 'النماذج',
        'description' => 'إنشاء وإدارة نماذج التواصل وجمع البيانات.',
        'icon' => 'assets/icons/stationery/005-clipboard.svg',
        'color' => 'yellow',
        'components' => [
            'index' => 'admin::page.content.forms.index',
            'detail' => 'admin::page.content.forms.detail',
        ],
    ],
    'store' => [
        'order' => 5,
        'active' => true,
        'default' => false,
        'sellable' => true,
        'slug' => 'store',
        'model_type' => 'product',
        'name' => 'المتجر الإلكتروني',
        'description' => 'إدارة المنتجات والتصنيفات وإعدادات المتجر.',
        'icon' => 'assets/icons/ecommerce/018-cart.svg',
        'color' => 'green',
        'components' => [
            'index' => 'admin::page.content.store.index',
            'detail' => 'admin::page.content.store.detail',
        ],
    ],
    'digital-products' => [
        'order' => 6,
        'active' => true,
        'default' => false,
        'sellable' => true,
        'slug' => 'digital-products',
        'model_type' => 'digital-product',
        'name' => 'المنتجات الرقمية',
        'description' => 'بيع وإدارة المنتجات الرقمية القابلة للتحميل والوصول الفوري.',
        'icon' => 'assets/icons/business/035-file.svg',
        'color' => 'red',
        'components' => [
            'index' => 'admin::page.content.digital-products.index',
            'detail' => 'admin::page.content.digital-products.detail',
        ],
    ],
    'digital-services' => [
        'order' => 7,
        'active' => true,
        'default' => false,
        'sellable' => true,
        'slug' => 'digital-services',
        'model_type' => 'digital-service',
        'name' => 'الخدمات الرقمية',
        'description' => 'بيع وإدارة الخدمات الرقمية مع تحديد مدة التسليم والسعر.',
        'icon' => 'assets/icons/business/015-cloud-network.svg',
        'color' => 'blue',
        'components' => [
            'index' => 'admin::page.content.digital-services.index',
            'detail' => 'admin::page.content.digital-services.detail',
        ],
    ],
    'services' => [
        'order' => 8,
        'active' => true,
        'default' => false,
        'sellable' => true,
        'slug' => 'services',
        'model_type' => 'service',
        'name' => 'خدمات بالساعة',
        'description' => 'عرض وإدارة الخدمات المقدمة بالساعة أو الحجز.',
        'icon' => 'assets/icons/business/025-team work.svg',
        'color' => 'teal',
        'components' => [
            'index' => 'admin::page.content.services.index',
            'detail' => 'admin::page.content.services.detail',
        ],
    ],
    'menu' => [
        'order' => 10,
        'active' => true,
        'default' => false,
        'sellable' => true,
        'slug' => 'menu',
        'model_type' => 'menu',
        'name' => 'أطعمة ومأكولات',
        'description' => 'إدارة أصناف وعناصر قائمة الطعام.',
        'icon' => 'assets/icons/business/059-teacup.svg',
        'color' => 'amber',
        'components' => [
            'index' => 'admin::page.content.menu.index',
            'detail' => 'admin::page.content.menu.detail',
        ],
    ],
    'unit-rental' => [
        'order' => 11,
        'active' => false,
        'default' => false,
        'sellable' => true,
        'slug' => 'unit-rental',
        'model_type' => 'unit',
        'name' => 'وحدات للتأجير',
        'description' => 'إدارة الوحدات المتاحة للتأجير.',
        'icon' => 'assets/icons/business/010-location.svg',
        'color' => 'lime',
        'components' => [
            'index' => 'admin::page.content.unit-rental.index',
            'detail' => 'admin::page.content.unit-rental.detail',
        ],
    ],
    // 'cv' => [
    //     'order' => 12,
    //     'slug' => 'cv',
    //     'model_type' => 'cv',
    //     'name' => 'السيرة الذاتية',
    //     'description' => 'إدارة بيانات السيرة الذاتية والخبرات والمهارات.',
    //     'icon' => 'assets/icons/stationery/011-id-card.svg',
    //     'color' => 'purple',
    //     'components' => [
    //         'index' => 'admin::page.content.cv.index',
    //         'detail' => 'admin::page.content.cv.detail',
    //     ],
    // ],
    'courses' => [
        'order' => 13,
        'active' => false,
        'default' => false,
        'sellable' => true,
        'slug' => 'courses',
        'model_type' => 'course',
        'name' => 'الدورات التدريبية',
        'description' => 'إنشاء وإدارة الدورات التدريبية والدروس والمحتوى التعليمي.',
        'icon' => 'assets/icons/business/011-presentation.svg',
        'color' => 'pink',
        'components' => [
            'index' => 'admin::page.content.courses.index',
            'detail' => 'admin::page.content.courses.detail',
        ],
    ],
];
