<?php

return [
    'pages' => [
        'order' => 1,
        'active' => true,
        'default' => true,
        'permanent' => true,
        'sellable' => false,
        'slug' => 'pages',
        'model_type' => 'page',
        'section' => 'content',
        'name' => 'الصفحات',
        'count_singular' => 'صفحة',
        'count_plural' => 'صفحات',
        'description' => 'إنشاء وإدارة صفحات الموقع الثابتة والمخصصة.',
        'icon' => 'assets/icons/ecommerce/031-content.svg',
        'color' => 'blue',
        'components' => [
            'index' => 'admin::page.content.pages.index',
            'detail' => 'admin::page.content.pages.detail',
        ],
    ],
    'blog' => [
        'order' => 2,
        'active' => true,
        'default' => false,
        'sellable' => false,
        'slug' => 'blog',
        'model_type' => 'blog',
        'section' => 'content',
        'name' => 'المدونة',
        'count_singular' => 'تدوينة',
        'count_plural' => 'تدوينات',
        'description' => 'كتابة ونشر المقالات وتنظيم التصنيفات.',
        'icon' => 'assets/icons/stationery/002-book.svg',
        'color' => 'orange',
        'components' => [
            'index' => 'admin::page.content.blog.index',
            'detail' => 'admin::page.content.blog.detail',
        ],
    ],
    'portfolio' => [
        'order' => 3,
        'active' => true,
        'default' => false,
        'sellable' => false,
        'slug' => 'portfolio',
        'model_type' => 'portfolio',
        'section' => 'trust',
        'name' => 'معرض الأعمال',
        'count_singular' => 'مشروع',
        'count_plural' => 'مشاريع',
        'description' => 'عرض وإدارة مشاريعك وأعمالك السابقة.',
        'icon' => 'assets/icons/business/047-portfolio.svg',
        'color' => 'violet',
        'components' => [
            'index' => 'admin::page.content.portfolio.index',
            'detail' => 'admin::page.content.portfolio.detail',
        ],
    ],
    'forms' => [
        'order' => 4,
        'active' => true,
        'default' => false,
        'permanent' => true,
        'sellable' => false,
        'slug' => 'forms',
        'model_type' => 'form',
        'section' => 'content',
        'name' => 'النماذج',
        'count_singular' => 'نموذج',
        'count_plural' => 'نماذج',
        'description' => 'إنشاء وإدارة نماذج التواصل وجمع البيانات.',
        'icon' => 'assets/icons/stationery/005-clipboard.svg',
        'color' => 'yellow',
        'components' => [
            'index' => 'admin::page.content.forms.index',
            'detail' => 'admin::page.content.forms.detail',
        ],
    ],
    'store' => [
        'order' => 5,
        'active' => true,
        'default' => false,
        'sellable' => true,
        'slug' => 'store', 
        'model_type' => 'product',
        'section' => 'sell',
        'name' => 'المتجر الإلكتروني',
        'count_singular' => 'منتج',
        'count_plural' => 'منتجات',
        'description' => 'لبيع المنتجات القابلة للشحن.',
        'icon' => 'assets/icons/ecommerce/018-cart.svg',
        'color' => 'green',
        'components' => [
            'index' => 'admin::page.content.store.index',
            'detail' => 'admin::page.content.store.detail',
        ],
    ],
    'digital-products' => [
        'order' => 6,
        'active' => true,
        'default' => false,
        'sellable' => true,
        'slug' => 'digital-products',
        'model_type' => 'digital-product',
        'section' => 'sell',
        'name' => 'المنتجات الرقمية',
        'count_singular' => 'منتج رقمي',
        'count_plural' => 'منتجات رقمية',
        'description' => 'لبيع المنتجات الرقمية القابلة للتحميل والوصول الفوري.',
        'icon' => 'assets/icons/business/035-file.svg',
        'color' => 'red',
        'components' => [
            'index' => 'admin::page.content.digital-products.index',
            'detail' => 'admin::page.content.digital-products.detail',
        ],
    ],
    'digital-services' => [
        'order' => 7,
        'active' => true,
        'default' => false,
        'sellable' => true,
        'slug' => 'digital-services',
        'model_type' => 'digital-service',
        'section' => 'sell',
        'name' => 'الخدمات الرقمية',
        'count_singular' => 'خدمة رقمية',
        'count_plural' => 'خدمات رقمية',
        'description' => 'لبيع الخدمات الرقمية مع تحديد مدة التسليم.',
        'icon' => 'assets/icons/business/015-cloud-network.svg',
        'color' => 'blue',
        'components' => [
            'index' => 'admin::page.content.digital-services.index',
            'detail' => 'admin::page.content.digital-services.detail',
        ],
    ],
    'services' => [
        'order' => 8,
        'active' => true,
        'default' => false,
        'sellable' => true,
        'slug' => 'services',
        'model_type' => 'service',
        'section' => 'sell',
        'name' => 'خدمات بالساعة',
        'count_singular' => 'خدمة',
        'count_plural' => 'خدمات',
        'description' => 'لبيع الخدمات المقدمة بالساعة وحجزها مع ربط مقدمي الخدمة.',
        'icon' => 'assets/icons/business/025-team work.svg',
        'color' => 'teal',
        'components' => [
            'index' => 'admin::page.content.services.index',
            'detail' => 'admin::page.content.services.detail',
        ],
    ],
    'menu' => [
        'order' => 10,
        'active' => true,
        'default' => false,
        'sellable' => true,
        'slug' => 'menu',
        'model_type' => 'menu',
        'section' => 'sell',
        'name' => 'أطعمة ومأكولات',
        'count_singular' => 'صنف',
        'count_plural' => 'أصناف',
        'description' => 'إدارة أصناف وعناصر قائمة الطعام.',
        'icon' => 'assets/icons/business/059-teacup.svg',
        'color' => 'amber',
        'components' => [
            'index' => 'admin::page.content.menu.index',
            'detail' => 'admin::page.content.menu.detail',
        ],
    ],
    'unit-rental' => [
        'order' => 11,
        'active' => false,
        'default' => false,
        'sellable' => true,
        'slug' => 'unit-rental',
        'model_type' => 'unit',
        'section' => 'sell',
        'name' => 'وحدات للتأجير',
        'count_singular' => 'وحدة',
        'count_plural' => 'وحدات',
        'description' => 'إدارة الوحدات المتاحة للتأجير.',
        'icon' => 'assets/icons/business/010-location.svg',
        'color' => 'lime',
        'components' => [
            'index' => 'admin::page.content.unit-rental.index',
            'detail' => 'admin::page.content.unit-rental.detail',
        ],
    ],
    // 'cv' => [
    //     'order' => 12,
    //     'slug' => 'cv',
    //     'model_type' => 'cv',
    //     'name' => 'السيرة الذاتية',
    //     'description' => 'إدارة بيانات السيرة الذاتية والخبرات والمهارات.',
    //     'icon' => 'assets/icons/stationery/011-id-card.svg',
    //     'color' => 'purple',
    //     'components' => [
    //         'index' => 'admin::page.content.cv.index',
    //         'detail' => 'admin::page.content.cv.detail',
    //     ],
    // ],
    'courses' => [
        'order' => 13,
        'active' => false,
        'default' => false,
        'sellable' => true,
        'slug' => 'courses',
        'model_type' => 'course',
        'section' => 'sell',
        'name' => 'الدورات التدريبية',
        'count_singular' => 'دورة',
        'count_plural' => 'دورات',
        'description' => 'إنشاء وإدارة الدورات التدريبية والدروس والمحتوى التعليمي.',
        'icon' => 'assets/icons/business/011-presentation.svg',
        'color' => 'pink',
        'components' => [
            'index' => 'admin::page.content.courses.index',
            'detail' => 'admin::page.content.courses.detail',
        ],
    ],
    'reviews' => [
        'order' => 14,
        'active' => false,
        'default' => false,
        'sellable' => false,
        'slug' => 'reviews',
        'model_type' => 'review',
        'section' => 'trust',
        'name' => 'التقييمات',
        'count_singular' => 'تقييم',
        'count_plural' => 'تقييمات',
        'description' => 'عرض قائمة التقييمات وآراء العملاء.',
        'icon' => 'assets/icons/ecommerce/006-badge.svg',
        'color' => 'amber',
    ],
];
